// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	role "idm/inner/role"

	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// Add provides a mock function with given fields: e
func (_m *Repo) Add(e *role.Entity) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*role.Entity) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteById provides a mock function with given fields: id
func (_m *Repo) DeleteById(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByIds provides a mock function with given fields: ids
func (_m *Repo) DeleteByIds(ids []int64) error {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]int64) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with no fields
func (_m *Repo) FindAll() ([]role.Entity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []role.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]role.Entity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []role.Entity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]role.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *Repo) FindById(id int64) (role.Entity, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 role.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (role.Entity, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) role.Entity); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(role.Entity)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIds provides a mock function with given fields: ids
func (_m *Repo) FindByIds(ids []int64) ([]role.Entity, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIds")
	}

	var r0 []role.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func([]int64) ([]role.Entity, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]int64) []role.Entity); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]role.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
